### ISSUE TITLE
Implement Add contact activity

### ISSUE THREAD

**Issue by TESLAA** [MuhametSmaili/androidPhoneBook#6]
As a PO i want to have an activity for adding new contacts

Options:
- You need to have NAME, NUMBER as fields
- You should not be able to add duplicated contacts
- You should show the user if NUMBER or NAME or BOTH are duplicated in case of duplication

**Comment by TESLAA** [comment]
Hi guys. please implement this issue faster, then we can go forward faster, today is the last day of this milestone

**Comment by TESLAA** [comment]
Since this task has been merged already by mistake please all of you go and read my comments, and one of you should fix them and make a new pull request
https://github.com/MuhametSmaili/androidPhoneBook/pull/19

**Comment by bkrmadtya** [comment]
Ok, working on it.

**Comment by bkrmadtya** [comment]
Resolved in #31

**Comment by Yarulika** [comment]
Sorry: just done
